In [1]:
import torch

In [6]:
x = torch.arange(4.0)

x

tensor([0., 1., 2., 3.])

In [7]:
# 存储梯度
x.requires_grad_(True)
x.grad

In [8]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [9]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [10]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])